version: "3.9"
   
services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    restart: on-failure
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_user
    ports:
      - "5432:5432"
    networks:
      - db
    env_file:
      - ./.env

  api:
    build:
      context: .
    restart: always
    volumes:
      - api-data:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - api
      - db
    env_file:
      - ./.env

volumes:
  postgres_data:
  api-data: 

networks:
  api:
    driver: bridge
  db: